version: '3.8'
services:

  # Spring Boot backend service
  backend:
    restart: always
    image: 'asterisk-backend'
    build:
      context: asterisk-backend/
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - database
      - redis-cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/<YOUR-DATABASE>
      - SPRING_DATASOURCE_USERNAME=<YOUR-DATABASE-USER>
      - SPRING_DATASOURCE_PASSWORD=<YOUR-DATABASE-PASSWORD>
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=redis-cache
      - SPRING_REDIS_PORT=6379
    networks:
      - backend
      - frontend

  # Angular website app service
  frontend-website:
    restart: always
    image: 'asterisk-frontend-website'
    ports:
      - "80:80"
    build:
      context: asterisk-frontend/
      target: website
    container_name: frontend-website
    depends_on:
      - backend
    networks:
      - frontend

  # Angular admin app service
  frontend-admin:
    restart: always
    image: 'asterisk-frontend-admin'
    ports:
      - "81:81"
    build:
      context: asterisk-frontend/
      target: admin
    container_name: frontend-admin
    depends_on:
      - backend
    networks:
      - frontend

  # Postgresql database service
  database:
    restart: always
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_USER=<YOUR-DATABASE-USER>
      - POSTGRES_PASSWORD=<YOUR-DATABASE-PASSWORD>
      - POSTGRES_DB=<YOUR-DATABASE>
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  # Redis cache service
  redis-cache:
    restart: always
    image: 'redis'
    ports:
      - "6379:6379"
    container_name: redis-cache
    networks:
      - backend


# Volumes
volumes:
  pgdata:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
